# Typos configuration for llm-d
# https://github.com/crate-ci/typos

[default.extend-words]
# Azure Kubernetes Service abbreviation
AKS = "AKS"
aks = "aks"
# Indian Standard Time / Istio abbreviation
IST = "IST"
# Abbreviation (e.g., 2nd â†’ ND)
ND = "ND"

# Pre-existing typos in codebase (to be fixed separately)
releas = "releas"
similiar = "similiar"
comparisson = "comparisson"
controlls = "controlls"
correspoinding = "correspoinding"
differet = "differet"
exernal = "exernal"
goolge = "goolge"
maxium = "maxium"
precomiled = "precomiled"
suppres = "suppres"
variabls = "variabls"
cluste = "cluste"
