name: Check Signed Commits
on: pull_request_target

jobs:
  signed-commits:
    uses: llm-d/llm-d-infra/.github/workflows/reusable-signed-commits.yml@main
    permissions:
      contents: read
      pull-requests: write
